carnival:
  colors:
    duck: (195, 144, 61)
    rabbit: (192, 192, 192)
    refill: (0, 0, 0)
    shooter: (66, 158, 130)
    owl: (146, 70, 192)
    pipes: (168, 48, 143)
    bonus: (204, 0, 0)
  obj_size: 20
  max_obj: 30


mspacman:
  colors:
    sue: (180, 122, 48)
    inky: (84, 184, 153)
    pinky: (198, 89, 179)
    blinky: (200, 72, 72)
    pacman: (210, 164, 74)
    fruit: (184, 50, 50)
    blue: (66, 114, 194)
    white: (214, 214, 214)
    life: (187, 187, 53)
    score: (195, 144, 61)
  obj_size: 20
  max_obj: 20

pong:
  colors:
    enemy: (213, 130, 74)
    player: (92, 186, 92)
    ball: (236, 236, 236)
  obj_size: 14
  splitted_objects: False
  max_obj: 8

spaceinvaders:
  colors:
    player: (50, 132, 50)
    planet: (151, 25, 122)
    enemy: (134, 134, 29)
    shield: (181, 83, 40)
    gfig: (50, 132, 50)
    yfig: (162, 134, 56)
  obj_size: 20
  splitted_objects: True
  max_obj: 40

tennis:
  colors:
    enemy: (117, 231, 194)
    player: (240, 128, 128)
    ball: (236, 236, 236)
    # ball_shadow: (74, 74, 74)
  obj_size: 15
  max_obj: 40
